language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

before_install:
  - export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129"
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"

    # Install .NET CLI
  - mkdir $DOTNET_INSTALL_DIR
  - curl -L $DOTNET_SDK_URL -o dotnet_package
  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR

    # Add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"


install:
  # Display dotnet version info
  - echo "Using dotnet:";
  - dotnet --info;

  # Restore dependencies
  - dotnet restore
  - dotnet build -f netcoreapp1.0 ./codevalr-api/src/codevalr

# whitelist
branches:
  only:
    - master
